services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        depends_on:
            - node
            - db

    web:
        image: nginx:latest
        container_name: nginx_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    node:
        image: node:latest
        container_name: node_js
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        command: npm run dev

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        ports:
            - "3306:3306"
        env_file:
            - .env
        volumes:
            - db_data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf  # Mount the custom my.cnf file

volumes:
    db_data:
